export const categories = ['All', 'Workshop', 'Tech', 'Cultural', 'Sports', 'Seminar', 'Hackathon']

const gradients = [
  'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
  'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
  'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
  'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
  'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)',
  'linear-gradient(135deg, #fccb90 0%, #d57eeb 100%)',
  'linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)',
  'linear-gradient(135deg, #f5576c 0%, #ff6f00 100%)',
  'linear-gradient(135deg, #667eea 0%, #43e97b 100%)',
]

const icons = [
  '💻', '🎨', '🚀', '🎭', '⚽', '📊', '🏆', '🎵', '🔬', '🌐',
]

export const events = [
  {
    id: 1,
    title: 'Cloud Computing Workshop',
    category: 'Workshop',
    date: '2026-08-10',
    time: '10:00 AM - 4:00 PM',
    venue: 'Computer Science Block, Lab 3',
    description: 'Hands-on workshop on AWS, Azure and GCP. Learn to deploy scalable cloud applications with industry experts from Amazon Web Services.',
    isPast: false,
    gradient: gradients[0],
    icon: icons[0],
  },
  {
    id: 2,
    title: 'CodeStorm Hackathon',
    category: 'Hackathon',
    date: '2026-08-05',
    time: '9:00 AM (24hrs)',
    venue: 'Main Auditorium',
    description: '24-hour coding challenge to build innovative solutions for real-world problems. Theme: Smart Campus Solutions. Teams of 3-4 members.',
    isPast: false,
    gradient: gradients[1],
    icon: icons[2],
  },
  {
    id: 3,
    title: 'Annual Cultural Fest – Udaan 2026',
    category: 'Cultural',
    date: '2026-08-20',
    time: '9:00 AM - 8:00 PM',
    venue: 'Open Air Theatre',
    description: 'The biggest cultural extravaganza of the year featuring dance, music, drama, fashion show, and literary competitions. Inter-college participation welcome.',
    isPast: false,
    gradient: gradients[2],
    icon: icons[3],
  },
  {
    id: 4,
    title: 'Inter-College Sports Tournament',
    category: 'Sports',
    date: '2026-08-25',
    time: '7:00 AM - 6:00 PM',
    venue: 'University Sports Complex',
    description: 'Annual sports meet featuring cricket, football, basketball, volleyball, athletics, and chess. Trophies and cash prizes for winners.',
    isPast: false,
    gradient: gradients[3],
    icon: icons[4],
  },
  {
    id: 5,
    title: 'AI & Machine Learning Seminar',
    category: 'Seminar',
    date: '2026-08-15',
    time: '2:00 PM - 5:00 PM',
    venue: 'Seminar Hall A',
    description: 'Expert talk on recent advances in AI and ML by Dr. Sundar Rajan, Chief AI Scientist at TechCorp. Topics include LLMs, computer vision, and ethical AI.',
    isPast: false,
    gradient: gradients[4],
    icon: icons[5],
  },
  {
    id: 6,
    title: 'UI/UX Design Sprint',
    category: 'Workshop',
    date: '2026-07-28',
    time: '10:00 AM - 5:00 PM',
    venue: 'Design Studio, Innovation Hub',
    description: 'A day-long design sprint to learn human-centered design, prototyping with Figma, and user research methods. No prior design experience needed.',
    isPast: true,
    gradient: gradients[5],
    icon: icons[1],
  },
  {
    id: 7,
    title: 'Blockchain & Web3 Summit',
    category: 'Tech',
    date: '2026-07-22',
    time: '11:00 AM - 4:00 PM',
    venue: 'Tech Park Auditorium',
    description: 'Explore blockchain technology, smart contracts, DeFi, and Web3 development. Live demo of building a dApp from scratch. Networking session included.',
    isPast: true,
    gradient: gradients[6],
    icon: icons[9],
  },
  {
    id: 8,
    title: 'Photography Exhibition',
    category: 'Cultural',
    date: '2026-07-18',
    time: '10:00 AM - 7:00 PM',
    venue: 'Art Gallery, Fine Arts Block',
    description: 'Annual photography exhibition showcasing student work. Categories: Nature, Portrait, Street Photography, and Campus Life. Winners announced at closing.',
    isPast: true,
    gradient: gradients[7],
    icon: icons[7],
  },
  {
    id: 9,
    title: 'Cybersecurity Capture The Flag',
    category: 'Tech',
    date: '2026-07-15',
    time: '9:00 AM - 6:00 PM',
    venue: 'CS Lab 5 & 6',
    description: 'CTF competition with challenges in cryptography, web exploitation, reverse engineering, and forensics. Prizes worth Rs. 50,000. Teams of 2.',
    isPast: true,
    gradient: gradients[8],
    icon: icons[0],
  },
  {
    id: 10,
    title: 'Data Science Bootcamp',
    category: 'Workshop',
    date: '2026-07-10',
    time: '10:00 AM - 5:00 PM',
    venue: 'Data Science Lab, CS Block',
    description: 'Intensive bootcamp covering Python, Pandas, Scikit-learn, and TensorFlow. Build real-world ML models. Certificate provided. Limited to 60 seats.',
    isPast: true,
    gradient: gradients[9],
    icon: icons[8],
  },
]
